### ISSUE TITLE
Return Value of Malloc is not chekced

### ISSUE THREAD

**Issue by hiteshlilhare** [rams76/pa193_peercoin_parser#8]
Problem identification | Return Value of malloc function call is not checked
Severity | Critical
Risk | High
Problem description |
 func_peercoin.c :   206 txn_hash1 = (unsigned char*)malloc(32 * sizeof(unsigned char));   func_peercoin.c :   207 txn_hash2 = (unsigned char*)malloc(32 * sizeof(unsigned char));   func_peercoin.c :   208 txn_hash =   (unsigned char*)malloc(32 * sizeof(unsigned   char));   func_peercoin.c :   209 txn =   (unsigned char*)malloc(txn_size * sizeof(unsigned   char));   func_peercoin.c :   247 script_Sig =   (unsigned char*)malloc(scriptSigLength * sizeof(unsigned   char))   func_peercoin.c :   274 scriptPubKey =   (unsigned char*)malloc(scriptPubKeyLength * sizeof(unsigned   char));   
func_peercoin.c :   293 block_Sig =   (unsigned char*)malloc(SigLength * sizeof(unsigned   char));   main_peercoin.c:   76 block1 = (uint8_t *) malloc(sizeof(uint8_t) * blockLength[0]);   
main_peercoin.c:   77 block2 = (uint8_t *) malloc(sizeof(uint8_t) * blockLength[1]);
Remediation | Return   value of malloc function call has to be checked

**Comment by rams76** [comment]
Patch accepted
